apacheopn:
  build: apache
  restart: always
  ports:
    - "80:80"
  volumes:
    - ./ambrieu:/var/www/ambrieu/
    - ./install:/var/install/
    - ./apache/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
    - ./apache/php.ini:/etc/php5/cli/conf.d/30-custom.ini
    - ./vhosts:/etc/apache2/sites-enabled
  links:
    - db
    - rabbitmq
db:
  image: mariadb
  restart: always
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=b1otope
    - MYSQL_DATABASE=blog_generator
    - MYSQL_USER=root
    - MYSQL_PASSWORD=b1otope
  volumes:
    - ./db:/var/lib/mariadb

phpmyadmin:
   image: corbinu/docker-phpmyadmin
   restart: always
   ports :
    - "8080:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=b1otope
   links:
    - db:mysql

rabbitmq:
   image: rabbitmq:3-management
   ports:
    - 15672:15672
