apache:
  build: apache
  restart: always
  ports:
    - "81:80"
  volumes:
    - ./html:/var/www/html/
    - ./vhosts:/etc/apache2/sites-enabled
    - ./tmp/opnkitchen:/tmp/opnkitchen
  links:
    - db
    - maildev
db:
  image: mariadb
  restart: always
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=opnK2015
    - MYSQL_DATABASE=opnkitchen
    - MYSQL_USER=opnKUser
    - MYSQL_PASSWORD=opnKPass
  volumes:
    - ./db:/etc/mysql/conf.d

phpmyadmin:
   image: corbinu/docker-phpmyadmin
   restart: always
   ports :
    - "8080:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=opnK2015
   links:
    - db:mysql


maildev:
  image: djfarrelly/maildev
  restart: always
  ports:
      - "1080:80"
